use_frameworks!

platform :ios, '13.0'

target 'RxTextureSupport_Example' do
  pod 'RxTextureSupport', :path => '../'
#  pod 'RxSwift', '~> 6.0'
#  pod 'RxDataSources', '~> 5.0'
#  pod 'Texture'
#  pod 'TextureSwiftSupport'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['CODE_SIGN_IDENTITY'] = ''
    end
  end
end
